INCLUDES=-I fol \
		 -I util \
         -I margrave \
		 -I margrave \
         -I margrave/policy \
		 -I margrave/vocab \
		 -I margrave/vocab/compile
CFLAGS=-cflags "-I +ocamlgraph"
LFLAGS=-lflags "-I +ocamlgraph"
LIBS=-lib graph
TARGETS=mc.byte

all:
	ocamlbuild $(INCLUDES) $(LIBS) $(TARGETS) $(CFLAGS) $(LFLAGS)

clean:
	ocamlbuild -clean
